name: CI/CD Prerelease
run-name: Prerelease

on:
  push:
    branches:
      - development
  workflow_dispatch:
    inputs:
      tag:
        type: choice
        description: "Choose a prerelease tag"
        options:
          - blizzard
          - dev

permissions:
  contents: write
  id-token: write

jobs:
  package-release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}

      - name: Build 🏗️
        uses: sliit-foss/actions/bun/build@main

      - name: Release 🚀
        uses: sliit-foss/actions/bun/publish@main
        env:
          TAG: ${{ inputs.tag || 'blizzard' }}
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

