name: CI Quality Checks
run-name: Quality Checks

on:
  pull_request:
    branches:
      - main
      - development
    types:
      - opened
      - reopened
      - synchronize

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4

      - name: Run commitlint 🟩
        uses: sliit-foss/actions/quality-checks/commitlint@v1.1

  lint:
    name: Enforce ESLint rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4

      - name: Run linter 📢
        uses: sliit-foss/actions/quality-checks/linter@v1.1
        with:
          package-manager: "bun"
