name: CI/CD Release
run-name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  package-release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}

      - name: Build 🏗️
        uses: sliit-foss/actions/bun/build@v1.1

      - name: Release 🚀
        uses: sliit-foss/actions/bun/publish@v1.1.1
        with:
          latest: true
          scrub_dependencies: true
        env:
          TAG: latest
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
  site-release:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v4

      - name: Build 🏗️
        uses: sliit-foss/actions/bun/build@v1.1
        with:
          storybooks: true

      - name: Create .nojekyll file 🚧
        run: touch ./storybook-static/.nojekyll
  
      - name: Fix 404 on page reload 🚧
        run: cp storybook-static/index.html storybook-static/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./storybook-static
          branch: main
          repository-name: mezh-hq/mezh-hq.github.io
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
